'use client'

import { useState } from 'react'
import { useFormFields } from '@payloadcms/ui'
import { isPrintSafeBaseUrl, scanUrl } from '../../lib/qr-url'

/**
 * Shows the printable code on the QR Codes edit screen, with download links.
 *
 * Staff produce artwork on print deadlines. Without this, getting a code into a
 * layout means asking an engineer, and that request arrives at the worst
 * possible moment every time.
 */
export function QrPreview() {
  const code = useFormFields(([fields]) => fields?.code?.value as string | undefined)
  // Off by default: the white background is the safe, print-ready one, and a
  // transparent code is only right when the person placing it controls what sits
  // behind it. See lib/qr-image.
  const [transparent, setTransparent] = useState(false)

  if (!code) {
    return (
      <div style={wrap}>
        <p style={hint}>Save this code first, then its printable image appears here.</p>
      </div>
    )
  }

  const bg = transparent ? '&transparent=1' : ''

  return (
    <div style={wrap}>
      {/* PNG purely because it displays at a predictable pixel size in the panel.
          The SVG below is the one that should reach a layout.

          Plain <img>, not next/image: this is generated by our own route, is
          never indexed, and is two-colour line art that the image optimiser
          cannot improve. Routing it through /_next/image would add a hop for no
          gain. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/qr/${code}?format=png&size=320${bg}`}
        alt={`QR code ${code}`}
        width={160}
        height={160}
        style={{
          display: 'block',
          border: '1px solid #ddd',
          borderRadius: 4,
          // A checkerboard when transparent, so the dropped-out background is
          // visible here rather than hidden behind a white panel.
          background: transparent
            ? 'repeating-conic-gradient(#ccc 0% 25%, #fff 0% 50%) 50% / 16px 16px'
            : '#fff',
        }}
      />
      <div>
        <p style={{ margin: '0 0 8px', fontSize: 13 }}>
          Scanning this opens <code>/g/{code}</code>, which redirects to whatever this code
          currently points at. Re-point it any time. The code itself never changes.
        </p>
        <p style={{ margin: 0, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          <a href={`/qr/${code}?download=1${bg}`} style={link}>
            Download SVG{transparent ? ' (transparent)' : ' for print'}
          </a>
          <a href={`/qr/${code}?format=png&size=2048&download=1${bg}`} style={link}>
            Download PNG{transparent ? ' (transparent)' : ''}
          </a>
        </p>
        <label
          style={{ ...hint, display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}
        >
          <input
            type="checkbox"
            checked={transparent}
            onChange={(event) => setTransparent(event.target.checked)}
          />
          Transparent background (drop the white, keep only the dark code)
        </label>
        <p style={hint}>
          {transparent
            ? 'Transparent has no white border to keep, so use it only where you control the background - a coloured layout or a photo - and not for print.'
            : 'Use the SVG for anything printed. Keep the white border around the code: cropping it is the most common reason a printed code stops scanning.'}
        </p>
        {isPrintSafeBaseUrl() ? null : (
          <p style={warn}>
            <strong>Not for print.</strong> This encodes <code>{scanUrl(code)}</code>, which readers
            cannot reach. Codes are only safe to print once NEXT_PUBLIC_SITE_URL is the live https
            domain, and the host cannot be changed after printing.
          </p>
        )}
      </div>
    </div>
  )
}

const wrap: React.CSSProperties = {
  display: 'flex',
  gap: 20,
  alignItems: 'flex-start',
  flexWrap: 'wrap',
  marginBottom: 24,
}

const link: React.CSSProperties = {
  fontSize: 13,
  textDecoration: 'underline',
}

const warn: React.CSSProperties = {
  margin: '12px 0 0',
  padding: '8px 12px',
  border: '2px solid #b00',
  borderRadius: 4,
  background: '#fff4f4',
  color: '#900',
  fontSize: 12,
  lineHeight: 1.5,
  maxWidth: '48ch',
}

const hint: React.CSSProperties = {
  margin: '8px 0 0',
  fontSize: 12,
  opacity: 0.7,
  maxWidth: '48ch',
}

export default QrPreview
