import { defineConfig } from 'vitest/config'

/**
 * Until now there was no config at all, so "122 tests pass" was a count with no
 * denominator - it told us nothing about what is actually covered.
 *
 * The exclude list below is deliberately short. It is tempting to exclude every
 * file that has no test so the percentage looks respectable, but that defeats
 * the point: the number exists to show where the gaps are, and the biggest gap
 * (src/access, the security boundary) has to stay in the denominator to be
 * visible.
 *
 * So only two things are excluded, and for the same reason in both cases -
 * nobody wrote them and nobody can fix their coverage:
 *
 *  - generated output (payload-types.ts, the admin importMap, migrations)
 *  - config and declaration files
 *
 * Collections, hooks, fields, lib and access all stay in, untested ones
 * included.
 *
 * # The thresholds are a ratchet, not a target
 *
 * They sit a few points below where the suite actually is, so their job is to
 * catch a regression - a deleted test file, a gutted module - rather than to
 * demand a number. `statements`/`lines` are low on purpose and are not a measure
 * of quality here: the denominator is every view and RSC file, most of which is
 * checked by the integration suite and by eye rather than by units. The floors
 * that mean something are `branches` and `functions`, which track the logic that
 * is genuinely unit-tested; those sit high because that code is well covered.
 *
 * CI enforces these through `pnpm --filter @vardenia/web test:coverage` - see the
 * Coverage floor step in .github/workflows/ci.yml. Raise them when a body of
 * tests lands that lifts the real number, so the ratchet only ever turns one way.
 */
export default defineConfig({
  /**
   * Components are rendered to static markup in tests, which means the test
   * transform has to compile JSX. tsconfig sets `jsx: "preserve"` because Next
   * does its own compiling, and esbuild reads that as "use the classic runtime"
   * - which needs `React` in scope and fails with "React is not defined" on
   * files that correctly do not import it.
   *
   * Next uses the automatic runtime, so this makes the tests compile JSX the
   * same way the application does.
   */
  esbuild: { jsx: 'automatic' },

  test: {
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],

    /**
     * next-intl has to go through Vite's resolver rather than Node's.
     *
     * v4 ships ESM only, and its build imports `next/server` and
     * `next/navigation` as bare specifiers. Under pnpm's isolated node_modules
     * those do not resolve from inside next-intl's own directory - `next` is a
     * peer dependency, so it is not linked there - and Node's ESM resolver
     * gives up with "Cannot find module .../next-intl/node_modules/next/server".
     *
     * It never came up under v3 because that build was CJS and went through a
     * resolver that walks up to the app's own node_modules. Nothing about the
     * application changed; only the module format did.
     *
     * Inlining makes Vite resolve those imports from the app, which is where
     * Next actually lives. The bundler does the same thing in a real build,
     * which is why `next build` was happy while the tests were not.
     */
    server: {
      deps: { inline: ['next-intl'] },
    },

    // The integration suite matches the glob above but needs a real database.
    // It has its own config and its own command, so that `pnpm test` stays
    // instant and dependency-free. See vitest.integration.config.ts.
    exclude: ['**/node_modules/**', 'src/integration/**'],

    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      reportsDirectory: './coverage',

      // A few points below the suite's current numbers (branches ~89, functions
      // ~58, lines ~32), so a real regression trips them and ordinary drift does
      // not. See the note above for why lines/statements are low and which of
      // these actually measure anything.
      thresholds: {
        statements: 28,
        lines: 28,
        functions: 54,
        branches: 84,
      },

      include: ['src/**/*.ts', 'src/**/*.tsx'],
      exclude: [
        // Generated. Regenerated by `payload generate:types` on every CI run.
        'src/payload-types.ts',
        'src/app/(payload)/admin/importMap.js',
        'src/migrations/**',

        // Config and declarations, not logic.
        'src/payload.config.ts',
        '**/*.d.ts',
        '**/*.test.ts',
        '**/*.test.tsx',

        // Test scaffolding, not shipped code.
        'src/integration/**',
        'src/seed/**',
      ],
    },
  },
})
