import { defineConfig } from 'vitest/config'

/**
 * Until now there was no config at all, so "122 tests pass" was a count with no
 * denominator - it told us nothing about what is actually covered.
 *
 * The exclude list below is deliberately short. It is tempting to exclude every
 * file that has no test so the percentage looks respectable, but that defeats
 * the point: the number exists to show where the gaps are, and the biggest gap
 * (src/access, the security boundary) has to stay in the denominator to be
 * visible.
 *
 * So only two things are excluded, and for the same reason in both cases -
 * nobody wrote them and nobody can fix their coverage:
 *
 *  - generated output (payload-types.ts, the admin importMap, migrations)
 *  - config and declaration files
 *
 * Collections, hooks, fields, lib and access all stay in, untested ones
 * included.
 *
 * No threshold is set yet. Adding tests for the access layer is queued and will
 * move these numbers a lot; picking a floor before that lands would either be
 * meaningless or would fail the build on day one.
 */
export default defineConfig({
  /**
   * Components are rendered to static markup in tests, which means the test
   * transform has to compile JSX. tsconfig sets `jsx: "preserve"` because Next
   * does its own compiling, and esbuild reads that as "use the classic runtime"
   * - which needs `React` in scope and fails with "React is not defined" on
   * files that correctly do not import it.
   *
   * Next uses the automatic runtime, so this makes the tests compile JSX the
   * same way the application does.
   */
  esbuild: { jsx: 'automatic' },

  test: {
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],

    // The integration suite matches the glob above but needs a real database.
    // It has its own config and its own command, so that `pnpm test` stays
    // instant and dependency-free. See vitest.integration.config.ts.
    exclude: ['**/node_modules/**', 'src/integration/**'],

    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      reportsDirectory: './coverage',
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      exclude: [
        // Generated. Regenerated by `payload generate:types` on every CI run.
        'src/payload-types.ts',
        'src/app/(payload)/admin/importMap.js',
        'src/migrations/**',

        // Config and declarations, not logic.
        'src/payload.config.ts',
        '**/*.d.ts',
        '**/*.test.ts',
        '**/*.test.tsx',

        // Test scaffolding, not shipped code.
        'src/integration/**',
        'src/seed/**',
      ],
    },
  },
})
