/**
 * A spreadsheet export, as data rather than as a file.
 *
 * # Why this is not a .csv on disk
 *
 * Because a directory of businesses is data and does not belong in a git
 * repository, and once the real export is excluded there is no reason for a
 * stand-in to be a file either. The tests need input, not a filesystem.
 *
 * As code it is also better input: every row can say which awkwardness it
 * exists to reproduce, which a CSV cannot. All twenty were taken from real
 * defects in the Keserwan export - each note below describes something that
 * file actually did.
 *
 * # Written out literally, never serialised
 *
 * These are string literals, not rows built by a helper. A fixture generated by
 * an escaping function shares its assumptions with the parser under test, so a
 * bug in one can cancel out a bug in the other and both tests pass.
 */

const LINES = [
  // The header. 23 columns, exactly as the real export writes them.
  'ID,Category,District,Class,Location,Name / Listing,Hotel Stars,Rating / 5,Rating as Written,Founder / Management,Phone,Price Range,Type / Activity,Usually When,Instagram / Page,Email,Languages,Overview / Description,Reviews,Additional Details,Source Paragraphs,Has Phone,Has Price',
  // Stars and a bracketed star count in the name, and a description full of commas.
  '1,Hotels,Keserwan District,A,Kfardebian,Highridge Mountain Lodge ★★★★★ (5-star hotel),5,4.6,Rating: 4.6/5,Founder: A Name,- +961 70 000 001,- $240 - $400,,,,,,"5-star mountain resort | Luxury rooms and suites, spa, heated pools",- | Guests praise the design.,,8–26,1,1',
  // Three stars, so the subcategory becomes boutique rather than luxury.
  '2,Hotels,Keserwan District,B,Ghazir,Smallgate Inn ★★★☆☆ (3-star hotel),3,4.0,Rating: 4.0/5,,+961 70 000 002,$60 - $110,,,,,,"Modest town hotel | Simple rooms, breakfast included",,,30–40,1,1',
  // Spans two districts, and its name ends in a town the Location column contradicts.
  '3,Hotels,Keserwan + Byblos / Jbeil Districts,A,Kaslik,Seaview Halat – Halat ★★★★☆ (4-star hotel),4,4.2,Rating: 4.2/5,,+961 70 000 003,$150 - $260,,,,,,Coastal hotel with a private beach,,,45–55,1,1',
  // A trailing location that does match Location, so it is stripped. No rating.
  '4,Guest Houses,Keserwan District,,"Faqra, Kfardebian","STONEHOUSE FAQRA — Faqra, Kfardebian",,,,Founder: NOT PUBLICLY LISTED,+971 50 000 004,Approximately $750+,,,,,,Private luxury mountain villa for eight guests,,,60–70,1,1',
  // The same, with an em dash.
  '5,Guest Houses,Keserwan District,,Faraya,Pinegrove Chalets — Faraya,,4.8,Rating: 4.8/5,Founder: Someone,+961 3 000 005,$120 - $300+,,,,,,"Mountain chalets with kitchens, Wi-Fi and modern interiors",,,75–85,1,1',
  // A dashed phrase that is part of the real name and must survive.
  '6,Guest Houses,Byblos / Jbeil District,,Jounieh,Casa Marina Guesthouse - Hosting Lebanon,,4.1,Rating: 4.1/5,,+961 3 000 006,$40,,,,,,A small guesthouse near the port,,,90–95,1,1',
  // A hyphenated place that is genuinely the name.
  '7,Restaurants,Keserwan District,B,ZOUK,Harbour Stories-Zouk Mosbeh,,4.3,Rating: 4.3/5,Founder: Not Publicly Listed,+961 81 000 007,,,,,,,"Italian kitchen, wood oven, and a terrace",,,100–108,1,0',
  // First of a duplicated name.
  '8,Restaurants,Keserwan District,C,Jounieh,Blue Table,,3.9,Rating: 3.9/5,,+961 9 000 008,,,,,,,,,,110–115,1,0',
  // Second of the duplicated name: its slug gets a numeric suffix.
  '9,Restaurants,Byblos / Jbeil District,C,Byblos,Blue Table,,4.4,Rating: 4.4/5,,+961 9 000 009,,,,,,,A second restaurant that happens to share a name,,,116–120,1,0',
  // Prose where a phone number should be. Not imported either way, but it must not break the row.
  '10,Restaurants,Keserwan District,,Harissa,Terrace Nine,,,,,No verified public number found,,,,,,,,,,121–125,0,0',
  // Two phone numbers, and a single activity that stays one tag.
  '11,Activities,Keserwan District,A,Jounieh ↔️ Harissa,Skyline Cableway — Cable-car ride,,4.5,Rating: 4.5/5,,+961 9 000 011 / +961 71 000 011,,Cable-car ride,,,,,A cable car between the bay and the hilltop shrine,,,130–140,1,0',
  // A phone number with a note appended, and an activity that is a comma-and-ampersand list.
  '12,Activities,Keserwan District,B,Tabarja,Riverbend Activity Park,,4.2,Rating: 4.2/5,,+961 70 000 012 for padel,,"Bowling, billiards, darts & games",,,,,,,,141–150,1,0',
  // Winter seasonality.
  '13,Activities,Keserwan District,B,Faraya,Summit Slopes,,4.7,Rating: 4.7/5,,+961 3 000 013,,"Skiing, snowboarding, hiking & summer mountain activities",Winter,,,,Ski slopes in winter and walking trails in summer,,,151–160,1,0',
  // A slash-separated activity, which becomes two tags. Instagram in the sheet's labelled form.
  '14,Tour Guides,Keserwan + Byblos / Jbeil Districts,,Ghineh,Sample Guide — Ghineh,,,,,+961 3 000 014,,International Mountain Guide / Mountaineer,,Instagram: @sampleguide | Page: @summitsample,,,,,,161–166,1,0',
  // A phone with a trailing note, and an Instagram/Page label variant.
  '15,Tour Guides,Keserwan District,,Keserwen Private Tours,Another Guide,,,,,+961 70 000 015 through a school,,Private Tour / Adventure Guide,,Instagram/Page: @anotherguide,,,,,,167–172,1,0',
  // No district at all, and a phone missing its plus.
  '16,Tour Guides,,,,Guide With No District,,,,,961 71 000 016.,,Local Guide,,,,,,,,173–176,1,0',
  // Months as a season: summer.
  '17,Festivals,Byblos / Jbeil District,,Jbeil / Byblos,Harbour Music Festival,,,,Founder: Organised by a committee,+961 9 000 017 / +961 3 000 017,,,July–August,,,,"Open-air music festival at the old port, with Lebanese and visiting acts",,,180–190,1,0',
  // September to October, which the site has no season for. Left blank and flagged.
  '18,Festivals,Byblos / Jbeil District,,Jbeil / Byblos,Autumn Harvest Days,,,,,Contact varies by yearly organizer,,,September–October,,,,A village harvest festival,,,191–196,0,0',
  // A date range in August.
  '19,Festivals,Keserwan District,,Harissa,Assumption Feast,,,,,Contact the shrine for the yearly program,,,August 14–15,,,,A pilgrimage feast held every August,,,197–202,0,0',
  // Year-round.
  '20,Festivals,Keserwan District,,Faraya,All Season Village Fair,,,,,+961 9 000 020,,,Year-round,,,,A market that runs all year,,,203–208,1,0',
]

/** The whole file, with the line endings a real export has. */
export const SAMPLE_CSV = LINES.join('\n')

/** How many listings SAMPLE_CSV maps to. Asserted rather than assumed. */
export const SAMPLE_ROWS = LINES.length - 1
