// ESLint 9 flat config, replacing .eslintrc.js.
//
// eslint-config-expo ships both formats; `flat` is the one that survives. This
// file is CommonJS because the package has no "type": "module" and Expo's own
// config is CJS too - .mjs here would fail to require it.
//
// Kept deliberately close to apps/web/eslint.config.mjs in shape, even though
// the underlying rule sets differ. The three shared packages use a common config
// (@vardenia/eslint-config); the two apps cannot, because each needs its
// framework's rules.
const expoConfig = require('eslint-config-expo/flat')

module.exports = [
  {
    // Build output and native projects. The ios/ and android/ directories are
    // generated by prebuild and gitignored, but they exist locally after a
    // native build and are not ours to lint.
    ignores: ['dist/**', '.expo/**', '.turbo/**', 'ios/**', 'android/**', 'expo-env.d.ts'],
  },

  ...expoConfig,
]
